version: '3.8'

services:
  users-service:
    build: ./user-service
    container_name: users-service_container
    ports:
      - '3000:3000'

  products-service:
    build: ./product-service
    container_name: products-service_container
    ports:
      - '3001:3001'

  orders-service:
    build: ./order-service
    container_name: orders-service_container
    ports:
      - '3002:3002'
    depends_on:
      - users-service

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service_container
    ports:
      - '3003:3003'

networks:
  default:
    name: microservice-network